<a href="https://colab.research.google.com/github/Chhayahedaoo23/PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!!")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. USing CPU")

GPU is available!!
Using GPU:Tesla T4


## Creating Tensor

In [ ]:
#Using empty
a=torch.empty(2,3)


In [ ]:
#Check Type
type(a)

torch.Tensor

In [ ]:
#Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using teansor
torch.tensor([[1,3,4], [3,8,9]])

tensor([[1, 3, 4],
        [3, 8, 9]])

In [ ]:
#other ways to define tensor
#arange
print("using arange->", torch.arange(0,10,2))

using arange-> tensor([0, 2, 4, 6, 8])


In [ ]:
# linspace
print("using linspace->",torch.linspace(0,10,10))

using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
# using eye[identity matrix]
print("using eye->", torch.eye(5))

using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# using full
print("Using full->", torch.full((3,3), 5))

Using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shape

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[      160330416, 136459167418160,               1],
        [              6,               0,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Tensor Data Type

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
b=torch.rand(2,3,4)
b

tensor([[[0.3404, 0.6162, 0.2128, 0.3003],
         [0.2531, 0.9703, 0.1657, 0.5613],
         [0.3958, 0.0418, 0.3300, 0.7184]],

        [[0.0396, 0.0426, 0.7209, 0.4208],
         [0.7945, 0.2120, 0.2847, 0.2880],
         [0.6264, 0.7407, 0.3752, 0.1771]]])

In [4]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [5]:
c=torch.rand(226,226,3)

In [6]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [7]:
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy And PyTorch

In [8]:
import numpy as np

In [9]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [10]:
b=a.numpy()
b

array([1, 2, 3])

In [11]:
type(b)

numpy.ndarray

In [12]:
c=np.array([1,2,3])

In [13]:
c

array([1, 2, 3])

In [14]:
torch.from_numpy(c)

tensor([1, 2, 3])