<a href="https://colab.research.google.com/github/Chhayahedaoo23/PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.8.0+cu126


In [4]:
if torch.cuda.is_available():
  print("GPU is available!!")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. USing CPU")

GPU is available!!
Using GPU:Tesla T4


## Creating Tensor

In [8]:
#Using empty
a=torch.empty(2,3)


In [9]:
#Check Type
type(a)

torch.Tensor

In [10]:
#Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
#using rand
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
#using teansor
torch.tensor([[1,3,4], [3,8,9]])

tensor([[1, 3, 4],
        [3, 8, 9]])

In [18]:
#other ways to define tensor
#arange
print("using arange->", torch.arange(0,10,2))

using arange-> tensor([0, 2, 4, 6, 8])


In [19]:
# linspace
print("using linspace->",torch.linspace(0,10,10))

using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [21]:
# using eye[identity matrix]
print("using eye->", torch.eye(5))

using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [22]:
# using full
print("Using full->", torch.full((3,3), 5))

Using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shape

In [23]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
x.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(x)

tensor([[      160330416, 136459167418160,               1],
        [              6,               0,               0]])

In [26]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])